// Question Bank - All ABO exam questions organized by domain
const questionBank = {
  general: [
    {
      q: "What is the condition where light focuses in front of the retina?",
      opts: ["Hyperopia", "Myopia", "Presbyopia", "Astigmatism"],
      correct: 1,
      exp: "Myopia (nearsightedness) occurs when light focuses in front of the retina, requiring minus lenses for correction.",
    },
    {
      q: "What is the average refractive power of the cornea?",
      opts: ["+20D", "+43D", "+60D", "+15D"],
      correct: 1,
      exp: "The cornea provides approximately +43 diopters of focusing power, about 2/3 of the eye's total refractive power.",
    },
    {
      q: "Presbyopia typically begins around what age?",
      opts: ["25 years", "35 years", "40 years", "50 years"],
      correct: 2,
      exp: "Presbyopia, the age-related loss of accommodation, typically begins around age 40 as the lens loses flexibility.",
    },
    {
      q: "Which part of the eye is responsible for central, detailed vision?",
      opts: ["Peripheral retina", "Macula", "Optic disc", "Ciliary body"],
      correct: 1,
      exp: "The macula is the central part of the retina responsible for sharp, detailed central vision.",
    },
    {
      q: "What refractive condition requires cylinder correction?",
      opts: ["Myopia", "Hyperopia", "Astigmatism", "Presbyopia"],
      correct: 2,
      exp: "Astigmatism is caused by irregular corneal curvature and requires cylinder correction in the prescription.",
    },
    {
      q: "What is anisometropia?",
      opts: [
        "Different prescription in each eye",
        "Unequal pupil size",
        "Color blindness",
        "Double vision",
      ],
      correct: 0,
      exp: "Anisometropia is a condition where the two eyes have significantly different refractive powers, requiring different prescription strengths.",
    },
    {
      q: "The crystalline lens is held in place by:",
      opts: ["Cornea", "Zonules", "Iris", "Vitreous"],
      correct: 1,
      exp: "Zonules (suspensory ligaments) attach the lens to the ciliary body, holding it in position and allowing it to change shape for accommodation.",
    },
    {
      q: "What is the normal range for intraocular pressure (IOP)?",
      opts: ["5-10 mmHg", "10-21 mmHg", "22-30 mmHg", "30-40 mmHg"],
      correct: 1,
      exp: "Normal IOP ranges from 10-21 mmHg. Elevated IOP (>21 mmHg) is a risk factor for glaucoma.",
    },
    {
      q: "Hyperopia is corrected with:",
      opts: ["Minus lenses", "Plus lenses", "Cylinder only", "Prism only"],
      correct: 1,
      exp: "Hyperopia (farsightedness) requires plus (+) lenses to add converging power so light focuses on the retina rather than behind it.",
    },
    {
      q: "The blind spot in the visual field corresponds to:",
      opts: ["Macula", "Fovea", "Optic disc", "Peripheral retina"],
      correct: 2,
      exp: "The optic disc (optic nerve head) has no photoreceptors, creating a blind spot in the visual field where the nerve exits the eye.",
    },
  ],
  optics: [
    {
      q: "Using Prentice's Rule, what prism is induced by a -4.00D lens decentered 3mm in?",
      opts: ["1.2Δ BO", "1.2Δ BI", "0.12Δ BO", "0.12Δ BI"],
      correct: 1,
      exp: "Δ = F × d = 4.00 × 0.3cm = 1.2Δ. Minus lens decentered IN creates BASE IN prism (opposite direction).",
    },
    {
      q: "What is the focal length of a +4.00D lens?",
      opts: ["4 meters", "0.25 meters", "25 centimeters", "Both B and C"],
      correct: 3,
      exp: "f = 1/D = 1/4 = 0.25 meters = 25 centimeters. Both answers are equivalent.",
    },
    {
      q: "Which lens material has the highest refractive index?",
      opts: ["CR-39", "Polycarbonate", "High-Index 1.67", "High-Index 1.74"],
      correct: 3,
      exp: "High-Index 1.74 has the highest refractive index (1.74), making it the thinnest lens material available.",
    },
    {
      q: "For plus lenses, the base direction of induced prism is:",
      opts: [
        "Opposite to decentration",
        "Same as decentration",
        "Always base down",
        "Independent of decentration",
      ],
      correct: 1,
      exp: "For plus lenses, the base direction is the SAME as the decentration direction. For minus lenses, it's opposite.",
    },
    {
      q: "What happens to lens thickness when refractive index increases?",
      opts: [
        "Increases",
        "Decreases",
        "Stays the same",
        "Depends on power only",
      ],
      correct: 1,
      exp: "Higher refractive index materials allow thinner lenses for the same prescription power.",
    },
    {
      q: "A -6.00D lens decentered 2mm out creates what prism?",
      opts: ["1.2Δ BI", "1.2Δ BO", "0.12Δ BI", "1.2Δ BD"],
      correct: 0,
      exp: "Δ = 6.00 × 0.2cm = 1.2Δ. Minus lens decentered OUT creates BASE IN prism (opposite direction).",
    },
    {
      q: "The Abbe value measures:",
      opts: [
        "Lens thickness",
        "Chromatic aberration",
        "Impact resistance",
        "UV protection",
      ],
      correct: 1,
      exp: "Abbe value measures chromatic aberration (color fringing). Higher values mean less aberration and better optical quality.",
    },
    {
      q: "To transpose -2.00 -1.50 x 090 to plus cylinder form:",
      opts: [
        "-3.50 +1.50 x 180",
        "-3.50 +1.50 x 090",
        "-2.00 +1.50 x 180",
        "-0.50 +1.50 x 180",
      ],
      correct: 0,
      exp: "Transposition: New sphere = -2.00 + (-1.50) = -3.50, New cyl = +1.50, New axis = 090 + 90 = 180.",
    },
    {
      q: "A lens with power +2.00 DS has what type of focal point?",
      opts: [
        "Virtual, in front of lens",
        "Real, behind lens",
        "No focal point",
        "At infinity",
      ],
      correct: 1,
      exp: "Plus lenses converge light to a real focal point behind the lens. Minus lenses have virtual focal points in front.",
    },
    {
      q: "Combining 2Δ BI OD and 3Δ BI OS results in:",
      opts: ["1Δ total", "5Δ total", "2.5Δ average", "Cannot combine"],
      correct: 1,
      exp: "Horizontal prism in the same direction (both BI) adds together: 2Δ + 3Δ = 5Δ total BI prism effect.",
    },
    {
      q: "What is the vertex distance compensation for a -10.00D lens at 12mm vs 14mm?",
      opts: [
        "No change needed",
        "Approximately -0.25D stronger",
        "Approximately +0.25D weaker",
        "Approximately -0.50D stronger",
      ],
      correct: 1,
      exp: "Moving a high minus lens further from the eye (12mm to 14mm) requires slightly more minus power, approximately -0.25D for -10.00D.",
    },
    {
      q: "A lens marked 6.00 base curve has approximately what power?",
      opts: ["+3.00D", "+6.00D", "+9.00D", "+12.00D"],
      correct: 0,
      exp: "Base curve in mm relates to power: D ≈ (n-1) × 1000/r. For n=1.530: (0.530 × 1000)/6 ≈ +3.00D on front surface.",
    },
    {
      q: "Spherical aberration is reduced by:",
      opts: [
        "Increasing lens diameter",
        "Aspheric lens design",
        "Higher Abbe value",
        "Thicker lens center",
      ],
      correct: 1,
      exp: "Aspheric designs flatten the lens periphery, reducing spherical aberration where light through lens edges focuses differently than center.",
    },
  ],
  dispensing: [
    {
      q: "What is the average adult pupillary distance (PD)?",
      opts: ["54-58mm", "60-64mm", "66-70mm", "72-76mm"],
      correct: 1,
      exp: "Average adult PD is 62-64mm. Men typically have slightly larger PDs (63-65mm) than women (60-62mm).",
    },
    {
      q: "Standard vertex distance is:",
      opts: ["8-10mm", "12-14mm", "16-18mm", "20-22mm"],
      correct: 1,
      exp: "Standard vertex distance is 12-14mm, the distance from the back of the lens to the front of the cornea.",
    },
    {
      q: "Pantoscopic tilt typically ranges from:",
      opts: ["0-4 degrees", "5-7 degrees", "8-12 degrees", "15-20 degrees"],
      correct: 2,
      exp: "Pantoscopic tilt (downward tilt of frame front) typically ranges from 8-12 degrees for optimal optics and appearance.",
    },
    {
      q: "For progressive lenses, the minimum fitting height is typically:",
      opts: ["12mm", "16mm", "18mm", "22mm"],
      correct: 2,
      exp: "Most progressive lenses require a minimum fitting height of 18mm to accommodate the progressive corridor.",
    },
    {
      q: "When measuring seg height for bifocals, you measure to:",
      opts: [
        "Center of pupil",
        "Lower lid margin",
        "Bottom of frame",
        "Top of segment",
      ],
      correct: 1,
      exp: "Seg height for bifocals is measured from the bottom of the lens to the lower lid margin (or slightly above).",
    },
    {
      q: "A frame marked 52-18-140 has:",
      opts: [
        "52mm eye size, 18mm bridge, 140mm temple",
        "52mm bridge, 18mm eye, 140mm temple",
        "52mm temple, 18mm bridge, 140mm eye",
        "52mm total width",
      ],
      correct: 0,
      exp: "Frame measurements follow the format: Eye Size (lens width) - Bridge Width - Temple Length. So 52-18-140 = 52mm eye, 18mm bridge, 140mm temple.",
    },
    {
      q: "When adjusting plastic frames, you should:",
      opts: [
        "Use cold water",
        "Heat the adjustment area",
        "Bend at room temperature",
        "Never adjust plastic",
      ],
      correct: 1,
      exp: "Plastic (zyl) frames require heat to adjust safely. Use a frame warmer or hot air to soften the material before bending to prevent cracking.",
    },
    {
      q: "The boxing system measures frame size by:",
      opts: [
        "Inside lens opening",
        "Smallest rectangle around lens",
        "Actual lens diameter",
        "Distance between temples",
      ],
      correct: 1,
      exp: "The boxing system uses the smallest rectangle that completely encloses the lens opening to determine eye size and other frame dimensions.",
    },
    {
      q: "For a patient with high minus prescription, recommend:",
      opts: [
        "Large frame",
        "Small frame with high-index",
        "Any frame style",
        "Rimless only",
      ],
      correct: 1,
      exp: "High minus lenses are thicker at edges. A smaller frame with high-index material minimizes edge thickness and weight for better cosmetics.",
    },
    {
      q: "Proper temple adjustment should have the temple:",
      opts: [
        "Touch behind ear immediately",
        "Follow head contour with bend at ear",
        "Remain straight to temple tip",
        "Angle away from head",
      ],
      correct: 1,
      exp: "Temples should follow the head contour and bend downward at the top of the ear, then extend along the ear without excessive pressure.",
    },
    {
      q: "Monocular PD is measured from:",
      opts: [
        "Pupil to pupil",
        "Center of bridge to each pupil",
        "Outer canthus to pupil",
        "Temporal limbus to bridge",
      ],
      correct: 1,
      exp: "Monocular PD measures from the center of the bridge (nasal midline) to the center of each pupil individually, allowing for asymmetric faces.",
    },
  ],
  products: [
    {
      q: "Which lens material is most impact-resistant?",
      opts: ["CR-39", "High-Index 1.67", "Polycarbonate", "Glass"],
      correct: 2,
      exp: "Polycarbonate is the most impact-resistant lens material, 10x more resistant than CR-39, making it ideal for children and safety glasses.",
    },
    {
      q: "Anti-reflective coating reduces surface reflections by approximately:",
      opts: ["2-4%", "5-7%", "8-12%", "15-20%"],
      correct: 2,
      exp: "AR coating reduces surface reflections from 8-12% to less than 1%, improving clarity and reducing glare.",
    },
    {
      q: "UV-B wavelengths range from:",
      opts: ["100-280nm", "280-315nm", "315-380nm", "380-500nm"],
      correct: 1,
      exp: "UV-B ranges from 280-315nm. UV-A is 315-380nm. Both should be blocked by quality lenses.",
    },
    {
      q: "Progressive lens design with the widest intermediate zone is called:",
      opts: ["Soft design", "Hard design", "Aspheric design", "Short corridor"],
      correct: 0,
      exp: "Soft design progressives have wider intermediate zones with more gradual power changes, while hard designs have narrower but longer zones.",
    },
    {
      q: "Photochromic lenses darken in response to:",
      opts: ["Heat", "UV light", "Visible light", "Infrared"],
      correct: 1,
      exp: "Photochromic lenses darken when exposed to UV light and return to clear when UV is removed.",
    },
    {
      q: "What does the first number in frame measurements represent?",
      opts: ["Bridge width", "Eye size", "Temple length", "Total width"],
      correct: 1,
      exp: "Frame measurements (e.g., 52-18-140) are: Eye Size - Bridge - Temple Length.",
    },
    {
      q: "Trivex lens material is characterized by:",
      opts: [
        "Highest index available",
        "Good impact resistance and optics",
        "Lowest cost",
        "Darkest tint capability",
      ],
      correct: 1,
      exp: "Trivex (n=1.532) combines excellent impact resistance with superior optical quality (high Abbe value ~45) and lighter weight than polycarbonate.",
    },
    {
      q: "A flat-top 28 bifocal has a segment:",
      opts: ["28mm wide", "28mm high", "28D add power", "2.8mm offset"],
      correct: 0,
      exp: "The number in bifocal names (FT-28, FT-35) refers to segment width in millimeters. FT-28 has a 28mm wide segment.",
    },
    {
      q: "Mirror coating on sunglasses:",
      opts: [
        "Blocks UV",
        "Reduces visible light transmission",
        "Improves scratch resistance",
        "Eliminates glare",
      ],
      correct: 1,
      exp: "Mirror coatings primarily reflect visible light, reducing transmission. They don't inherently block UV (needs separate UV coating/material).",
    },
    {
      q: "The minimum center thickness for CR-39 lenses is typically:",
      opts: ["0.5mm", "1.0mm", "2.0mm", "3.0mm"],
      correct: 2,
      exp: "CR-39 lenses typically require 2.0mm minimum center thickness for structural integrity and edging stability, especially in minus prescriptions.",
    },
    {
      q: "Polarized lenses are most beneficial for:",
      opts: [
        "Night driving",
        "Computer use",
        "Water/snow glare",
        "Indoor activities",
      ],
      correct: 2,
      exp: "Polarized lenses eliminate horizontally polarized light (glare) reflected from flat surfaces like water, snow, roads, making them ideal for outdoor activities.",
    },
    {
      q: "High-index 1.67 lenses are approximately what percentage thinner than CR-39?",
      opts: ["10%", "20%", "30%", "40%"],
      correct: 2,
      exp: "High-index 1.67 lenses are approximately 30% thinner than CR-39 (1.498) for the same prescription power and size.",
    },
  ],
};
